version: '3.3'
services:
    swagger-editor:
      image: swaggerapi/swagger-editor
      container_name: "swagger-editor"
      ports:
        - "9081:8080"

    swagger-ui:
      image: swaggerapi/swagger-ui
      container_name: "swagger-ui"
      ports:
        - "9082:8080"
      volumes:
        - ./api_ref:/usr/share/nginx/html/api_ref
      environment:
        API_URL: api_ref/petstore_api.yaml

    swagger-mock:
      image: stoplight/prism:3
      container_name: "mock-server"
      ports:
        - "9083:4010"
      command: mock -h 0.0.0.0 /petstore_api.yaml
      volumes:
        - ./petstore_api.yaml:/petstore_api.yaml
